matrix:
  include:
    - language: go
      go: "1.11"
      before_install:
       - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh  
       - go get golang.org/x/lint/golint
       - go get sigs.k8s.io/controller-runtime/pkg/envtest
      install:
        - export GOPATH=$PWD
        - echo installgopath $GOPATH
        - cd src/github.com/cloudfoundry-incubator/webhooks
        - dep ensure
      script:
        - cd pkg/webhooks/manager
        - gofmt -l .
        - go vet
        - golint
        - echo script current working dir $PWD
        - go test -cover -- stderrthreshold=FATAL
    - language: ruby
      install:
              - "./scripts/update"
              - "gem install bosh_cli --no-document"
      script:
              - "bosh create release --force --name service-fabrik"
